import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
// import BootstrapClient from "@/utils/bootstrapclient";
import { Analytics } from "@vercel/analytics/react";
import "@/utils/styles.css"
import "@/utils/custom.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Analytics />
        {children}
        {/* <BootstrapClient /> */}
      </body>
    </html>
  );
}
